In [1]:
import sys
import os
from pathlib import Path
from dotenv import load_dotenv
import pandas as pd
import optuna
import importlib

sys.path.append(os.path.abspath(".."))

import src.models.xgb.xgb_cv_trainer as cv
import src.models.xgb.xgb_objective as ob
import src.utils.run_optuna as op

In [2]:
# Load data
env_path = Path.cwd().parent / ".env"
load_dotenv(dotenv_path=env_path)
url = os.environ.get("OPTUNA_STORAGE_URL")

tr_df16 = pd.read_parquet("../artifacts/features/base/tr_df16.parquet")

In [ ]:
# Tuning
importlib.reload(cv)
importlib.reload(op)
objective = ob.create_objective(
    tr_df16,
    early_stopping_rounds=200,
    n_jobs=10
)

op.run_optuna_search(
    objective,
    n_trials=10,
    n_jobs=1,
    direction="maximize",
    study_name="xgb_v7",
    storage=url,
    sampler=optuna.samplers.TPESampler(
        n_startup_trials=20, seed=42)
)

[I 2025-08-23 17:27:44,864] Using an existing study with name 'xgb_v7' instead of creating a new one.

  0%|          | 0/10 [00:00<?, ?it/s]

[0]	train-auc:0.96085	eval-auc:0.95773
[100]	train-auc:0.97459	eval-auc:0.97039
[200]	train-auc:0.97757	eval-auc:0.97147
[300]	train-auc:0.97993	eval-auc:0.97228
[400]	train-auc:0.98183	eval-auc:0.97292
[500]	train-auc:0.98340	eval-auc:0.97335
[600]	train-auc:0.98467	eval-auc:0.97362
[700]	train-auc:0.98578	eval-auc:0.97384
[800]	train-auc:0.98674	eval-auc:0.97399
[900]	train-auc:0.98759	eval-auc:0.97410
[1000]	train-auc:0.98834	eval-auc:0.97418
[1100]	train-auc:0.98906	eval-auc:0.97424
[1200]	train-auc:0.98975	eval-auc:0.97429
[1300]	train-auc:0.99036	eval-auc:0.97434
[1400]	train-auc:0.99100	eval-auc:0.97438
[1500]	train-auc:0.99154	eval-auc:0.97442
[1600]	train-auc:0.99209	eval-auc:0.97445
[1700]	train-auc:0.99259	eval-auc:0.97446
[1800]	train-auc:0.99307	eval-auc:0.97448
[1900]	train-auc:0.99354	eval-auc:0.97450
[2000]	train-auc:0.99396	eval-auc:0.97450
[2100]	train-auc:0.99437	eval-auc:0.97451
[2200]	train-auc:0.99475	eval-auc:0.97452
[2300]	train-auc:0.99514	eval-auc:0.97453
[2400]	train-auc:0.99550	eval-auc:0.97455
[2500]	train-auc:0.99584	eval-auc:0.97455
[2600]	train-auc:0.99614	eval-auc:0.97455
[2700]	train-auc:0.99643	eval-auc:0.97456
[2800]	train-auc:0.99668	eval-auc:0.97456
[2900]	train-auc:0.99693	eval-auc:0.97456
[3000]	train-auc:0.99716	eval-auc:0.97456
[3100]	train-auc:0.99740	eval-auc:0.97456
[3108]	train-auc:0.99741	eval-auc:0.97456
Training time: 00:02:25
Train AUC: 0.99694
Valid AUC: 0.97456
[I 2025-08-23 17:30:10,106] Trial 11 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.010194731720346375, 'max_depth': 17, 'min_child_weight': 18.595460827108802, 'colsample_bytree': 0.5145545528968135, 'subsample': 0.8738821516811326, 'reg_alpha': 0.6912957656418114, 'reg_lambda': 9.699337364190377}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.96004	eval-auc:0.95798
[100]	train-auc:0.97280	eval-auc:0.97044
[200]	train-auc:0.97494	eval-auc:0.97189
[300]	train-auc:0.97660	eval-auc:0.97274
[400]	train-auc:0.97795	eval-auc:0.97324
[500]	train-auc:0.97911	eval-auc:0.97355
[600]	train-auc:0.98015	eval-auc:0.97372
[700]	train-auc:0.98108	eval-auc:0.97383
[800]	train-auc:0.98194	eval-auc:0.97394
[900]	train-auc:0.98275	eval-auc:0.97401
[1000]	train-auc:0.98352	eval-auc:0.97406
[1100]	train-auc:0.98422	eval-auc:0.97410
[1200]	train-auc:0.98492	eval-auc:0.97413
[1300]	train-auc:0.98557	eval-auc:0.97414
[1400]	train-auc:0.98619	eval-auc:0.97415
[1500]	train-auc:0.98677	eval-auc:0.97415
[1600]	train-auc:0.98734	eval-auc:0.97416
[1700]	train-auc:0.98787	eval-auc:0.97418
[1800]	train-auc:0.98839	eval-auc:0.97418
[1900]	train-auc:0.98888	eval-auc:0.97418
[1968]	train-auc:0.98920	eval-auc:0.97416
Training time: 00:01:08
Train AUC: 0.98823
Valid AUC: 0.97419
[I 2025-08-23 17:31:19,061] Trial 12 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.01749080237694725, 'max_depth': 29, 'min_child_weight': 73.1993941811405, 'colsample_bytree': 0.47959754525911097, 'subsample': 0.5624074561769746, 'reg_alpha': 0.0007479811637240149, 'reg_lambda': 0.00019517224641449495}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.95914	eval-auc:0.95651
[100]	train-auc:0.97433	eval-auc:0.97103
[200]	train-auc:0.97751	eval-auc:0.97260
[300]	train-auc:0.97984	eval-auc:0.97335
[400]	train-auc:0.98153	eval-auc:0.97373
[500]	train-auc:0.98299	eval-auc:0.97395
[600]	train-auc:0.98424	eval-auc:0.97405
[700]	train-auc:0.98537	eval-auc:0.97412
[800]	train-auc:0.98642	eval-auc:0.97418
[900]	train-auc:0.98736	eval-auc:0.97421
[1000]	train-auc:0.98823	eval-auc:0.97424
[1100]	train-auc:0.98907	eval-auc:0.97425
[1200]	train-auc:0.98984	eval-auc:0.97426
[1300]	train-auc:0.99055	eval-auc:0.97426
[1400]	train-auc:0.99121	eval-auc:0.97425
[1500]	train-auc:0.99184	eval-auc:0.97424
[1534]	train-auc:0.99204	eval-auc:0.97423
Training time: 00:00:54
Train AUC: 0.99077
Valid AUC: 0.97427
[I 2025-08-23 17:32:13,333] Trial 13 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.0273235229154987, 'max_depth': 19, 'min_child_weight': 70.80725777960456, 'colsample_bytree': 0.3061753482887407, 'subsample': 0.8879639408647977, 'reg_alpha': 4.606739059380685, 'reg_lambda': 0.0011526449540315614}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.95700	eval-auc:0.95485
[100]	train-auc:0.97186	eval-auc:0.96985
[200]	train-auc:0.97337	eval-auc:0.97093
[300]	train-auc:0.97453	eval-auc:0.97179
[400]	train-auc:0.97547	eval-auc:0.97238
[500]	train-auc:0.97627	eval-auc:0.97282
[600]	train-auc:0.97685	eval-auc:0.97309
[700]	train-auc:0.97739	eval-auc:0.97329
[800]	train-auc:0.97783	eval-auc:0.97343
[900]	train-auc:0.97823	eval-auc:0.97355
[1000]	train-auc:0.97864	eval-auc:0.97364
[1100]	train-auc:0.97902	eval-auc:0.97373
[1200]	train-auc:0.97937	eval-auc:0.97380
[1300]	train-auc:0.97969	eval-auc:0.97386
[1400]	train-auc:0.98001	eval-auc:0.97391
[1500]	train-auc:0.98034	eval-auc:0.97395
[1600]	train-auc:0.98065	eval-auc:0.97398
[1700]	train-auc:0.98098	eval-auc:0.97403
[1800]	train-auc:0.98128	eval-auc:0.97406
[1900]	train-auc:0.98157	eval-auc:0.97409
[2000]	train-auc:0.98187	eval-auc:0.97412
[2100]	train-auc:0.98214	eval-auc:0.97414
[2200]	train-auc:0.98243	eval-auc:0.97416
[2300]	train-auc:0.98268	eval-auc:0.97418
[2400]	train-auc:0.98296	eval-auc:0.97420
[2500]	train-auc:0.98322	eval-auc:0.97422
[2600]	train-auc:0.98347	eval-auc:0.97424
[2700]	train-auc:0.98374	eval-auc:0.97425
[2800]	train-auc:0.98399	eval-auc:0.97427
[2900]	train-auc:0.98424	eval-auc:0.97428
[3000]	train-auc:0.98449	eval-auc:0.97429
[3100]	train-auc:0.98473	eval-auc:0.97430
[3200]	train-auc:0.98496	eval-auc:0.97431
[3300]	train-auc:0.98517	eval-auc:0.97432
[3400]	train-auc:0.98538	eval-auc:0.97432
[3500]	train-auc:0.98560	eval-auc:0.97432
[3600]	train-auc:0.98581	eval-auc:0.97433
[3700]	train-auc:0.98604	eval-auc:0.97432
[3794]	train-auc:0.98626	eval-auc:0.97432
Training time: 00:01:10
Train AUC: 0.98580
Valid AUC: 0.97433
[I 2025-08-23 17:33:23,663] Trial 14 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.013636499344142012, 'max_depth': 8, 'min_child_weight': 30.42422429595377, 'colsample_bytree': 0.45742692948967134, 'subsample': 0.6727780074568463, 'reg_alpha': 0.0042803877709703415, 'reg_lambda': 0.11462107403425033}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.96102	eval-auc:0.95839
[100]	train-auc:0.97431	eval-auc:0.97064
[200]	train-auc:0.97605	eval-auc:0.97165
[300]	train-auc:0.97739	eval-auc:0.97244
[400]	train-auc:0.97845	eval-auc:0.97294
[500]	train-auc:0.97938	eval-auc:0.97333
[600]	train-auc:0.98008	eval-auc:0.97357
[700]	train-auc:0.98070	eval-auc:0.97373
[800]	train-auc:0.98126	eval-auc:0.97386
[900]	train-auc:0.98181	eval-auc:0.97396
[1000]	train-auc:0.98230	eval-auc:0.97405
[1100]	train-auc:0.98277	eval-auc:0.97411
[1200]	train-auc:0.98322	eval-auc:0.97417
[1300]	train-auc:0.98365	eval-auc:0.97421
[1400]	train-auc:0.98406	eval-auc:0.97424
[1500]	train-auc:0.98447	eval-auc:0.97429
[1600]	train-auc:0.98488	eval-auc:0.97432
[1700]	train-auc:0.98525	eval-auc:0.97434
[1800]	train-auc:0.98565	eval-auc:0.97435
[1900]	train-auc:0.98601	eval-auc:0.97437
[2000]	train-auc:0.98634	eval-auc:0.97437
[2100]	train-auc:0.98671	eval-auc:0.97439
[2200]	train-auc:0.98704	eval-auc:0.97440
[2300]	train-auc:0.98737	eval-auc:0.97441
[2400]	train-auc:0.98768	eval-auc:0.97442
[2500]	train-auc:0.98802	eval-auc:0.97444
[2600]	train-auc:0.98831	eval-auc:0.97445
[2700]	train-auc:0.98864	eval-auc:0.97445
[2800]	train-auc:0.98894	eval-auc:0.97446
[2900]	train-auc:0.98922	eval-auc:0.97446
[3000]	train-auc:0.98951	eval-auc:0.97446
[3012]	train-auc:0.98954	eval-auc:0.97446
Training time: 00:01:17
Train AUC: 0.98897
Valid AUC: 0.97446
[I 2025-08-23 17:34:40,914] Trial 15 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.012789877213040837, 'max_depth': 11, 'min_child_weight': 36.63618432936917, 'colsample_bytree': 0.43682099526511076, 'subsample': 0.8140703845572055, 'reg_alpha': 0.0013139671458262555, 'reg_lambda': 0.03725393839578886}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.93388	eval-auc:0.93358
[100]	train-auc:0.96734	eval-auc:0.96680
[200]	train-auc:0.96913	eval-auc:0.96847
[300]	train-auc:0.97036	eval-auc:0.96960
[400]	train-auc:0.97114	eval-auc:0.97035
[500]	train-auc:0.97174	eval-auc:0.97094
[600]	train-auc:0.97218	eval-auc:0.97132
[700]	train-auc:0.97255	eval-auc:0.97163
[800]	train-auc:0.97284	eval-auc:0.97185
[900]	train-auc:0.97309	eval-auc:0.97204
[1000]	train-auc:0.97330	eval-auc:0.97218
[1100]	train-auc:0.97350	eval-auc:0.97231
[1200]	train-auc:0.97369	eval-auc:0.97243
[1300]	train-auc:0.97384	eval-auc:0.97252
[1400]	train-auc:0.97399	eval-auc:0.97261
[1500]	train-auc:0.97413	eval-auc:0.97269
[1600]	train-auc:0.97426	eval-auc:0.97275
[1700]	train-auc:0.97438	eval-auc:0.97282
[1800]	train-auc:0.97450	eval-auc:0.97288
[1900]	train-auc:0.97462	eval-auc:0.97294
[2000]	train-auc:0.97473	eval-auc:0.97298
[2100]	train-auc:0.97482	eval-auc:0.97303
[2200]	train-auc:0.97492	eval-auc:0.97308
[2300]	train-auc:0.97502	eval-auc:0.97311
[2400]	train-auc:0.97512	eval-auc:0.97316
[2500]	train-auc:0.97522	eval-auc:0.97319
[2600]	train-auc:0.97530	eval-auc:0.97322
[2700]	train-auc:0.97539	eval-auc:0.97325
[2800]	train-auc:0.97548	eval-auc:0.97328
[2900]	train-auc:0.97556	eval-auc:0.97331
[3000]	train-auc:0.97564	eval-auc:0.97334
[3100]	train-auc:0.97572	eval-auc:0.97336
[3200]	train-auc:0.97580	eval-auc:0.97338
[3300]	train-auc:0.97588	eval-auc:0.97340
[3400]	train-auc:0.97595	eval-auc:0.97343
[3500]	train-auc:0.97603	eval-auc:0.97345
[3600]	train-auc:0.97610	eval-auc:0.97346
[3700]	train-auc:0.97617	eval-auc:0.97348
[3800]	train-auc:0.97624	eval-auc:0.97349
[3900]	train-auc:0.97631	eval-auc:0.97351
[4000]	train-auc:0.97637	eval-auc:0.97352
[4100]	train-auc:0.97644	eval-auc:0.97353
[4200]	train-auc:0.97651	eval-auc:0.97355
[4300]	train-auc:0.97658	eval-auc:0.97356
[4400]	train-auc:0.97664	eval-auc:0.97357
[4500]	train-auc:0.97670	eval-auc:0.97357
[4600]	train-auc:0.97676	eval-auc:0.97358
[4700]	train-auc:0.97683	eval-auc:0.97360
[4800]	train-auc:0.97689	eval-auc:0.97361
[4900]	train-auc:0.97696	eval-auc:0.97362
[5000]	train-auc:0.97702	eval-auc:0.97363
[5100]	train-auc:0.97708	eval-auc:0.97364
[5200]	train-auc:0.97714	eval-auc:0.97365
[5300]	train-auc:0.97720	eval-auc:0.97366
[5400]	train-auc:0.97726	eval-auc:0.97367
[5500]	train-auc:0.97732	eval-auc:0.97368
[5600]	train-auc:0.97737	eval-auc:0.97368
[5700]	train-auc:0.97743	eval-auc:0.97369
[5800]	train-auc:0.97749	eval-auc:0.97370
[5900]	train-auc:0.97754	eval-auc:0.97370
[6000]	train-auc:0.97760	eval-auc:0.97371
[6100]	train-auc:0.97765	eval-auc:0.97372
[6200]	train-auc:0.97771	eval-auc:0.97373
[6300]	train-auc:0.97777	eval-auc:0.97373
[6400]	train-auc:0.97782	eval-auc:0.97374
[6500]	train-auc:0.97787	eval-auc:0.97375
[6600]	train-auc:0.97793	eval-auc:0.97375
[6700]	train-auc:0.97798	eval-auc:0.97375
[6800]	train-auc:0.97803	eval-auc:0.97376
[6900]	train-auc:0.97808	eval-auc:0.97376
[7000]	train-auc:0.97813	eval-auc:0.97377
[7100]	train-auc:0.97818	eval-auc:0.97377
[7200]	train-auc:0.97823	eval-auc:0.97378
[7300]	train-auc:0.97828	eval-auc:0.97379
[7400]	train-auc:0.97833	eval-auc:0.97379
[7500]	train-auc:0.97838	eval-auc:0.97379
[7600]	train-auc:0.97843	eval-auc:0.97379
[7700]	train-auc:0.97848	eval-auc:0.97380
[7800]	train-auc:0.97853	eval-auc:0.97380
[7900]	train-auc:0.97858	eval-auc:0.97380
[8000]	train-auc:0.97863	eval-auc:0.97380
[8009]	train-auc:0.97863	eval-auc:0.97380
Training time: 00:01:41
Train AUC: 0.97853
Valid AUC: 0.97380
[I 2025-08-23 17:36:22,191] Trial 16 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.02184829137724085, 'max_depth': 4, 'min_child_weight': 60.75448519014384, 'colsample_bytree': 0.35115723710618746, 'subsample': 0.5260206371941119, 'reg_alpha': 20.687771209004854, 'reg_lambda': 6.732248920775331}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.96201	eval-auc:0.95742
[100]	train-auc:0.97937	eval-auc:0.97203
[200]	train-auc:0.98249	eval-auc:0.97319
[300]	train-auc:0.98474	eval-auc:0.97364
[400]	train-auc:0.98651	eval-auc:0.97384
[500]	train-auc:0.98813	eval-auc:0.97398
[600]	train-auc:0.98948	eval-auc:0.97404
[700]	train-auc:0.99078	eval-auc:0.97405
[800]	train-auc:0.99186	eval-auc:0.97407
[900]	train-auc:0.99292	eval-auc:0.97406
[999]	train-auc:0.99387	eval-auc:0.97406
Training time: 00:00:34
Train AUC: 0.99186
Valid AUC: 0.97407
[I 2025-08-23 17:36:59,844] Trial 17 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.02616794696232922, 'max_depth': 11, 'min_child_weight': 9.767211400638388, 'colsample_bytree': 0.505269907953647, 'subsample': 0.6760609974958405, 'reg_alpha': 0.0004826869005553143, 'reg_lambda': 0.029914693021302164}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.96287	eval-auc:0.95814
[100]	train-auc:0.97569	eval-auc:0.97085
[200]	train-auc:0.97812	eval-auc:0.97184
[300]	train-auc:0.98024	eval-auc:0.97264
[400]	train-auc:0.98212	eval-auc:0.97318
[500]	train-auc:0.98380	eval-auc:0.97357
[600]	train-auc:0.98526	eval-auc:0.97382
[700]	train-auc:0.98653	eval-auc:0.97398
[800]	train-auc:0.98768	eval-auc:0.97411
[900]	train-auc:0.98877	eval-auc:0.97420
[1000]	train-auc:0.98980	eval-auc:0.97426
[1100]	train-auc:0.99072	eval-auc:0.97430
[1200]	train-auc:0.99155	eval-auc:0.97433
[1300]	train-auc:0.99230	eval-auc:0.97434
[1400]	train-auc:0.99297	eval-auc:0.97436
[1500]	train-auc:0.99360	eval-auc:0.97438
[1600]	train-auc:0.99419	eval-auc:0.97438
[1700]	train-auc:0.99473	eval-auc:0.97439
[1800]	train-auc:0.99520	eval-auc:0.97438
[1900]	train-auc:0.99565	eval-auc:0.97438
[1925]	train-auc:0.99576	eval-auc:0.97438
Training time: 00:01:42
Train AUC: 0.99485
Valid AUC: 0.97439
[I 2025-08-23 17:38:42,164] Trial 18 finished with value: 0.9745643174870363 and parameters: {'learning_rate': 0.010687770422304368, 'max_depth': 28, 'min_child_weight': 25.87799816000169, 'colsample_bytree': 0.49875668530619455, 'subsample': 0.6246844304357644, 'reg_alpha': 0.0819317543485537, 'reg_lambda': 0.05414413211338523}. Best is trial 11 with value: 0.9745643174870363.
[0]	train-auc:0.96086	eval-auc:0.95894
[100]	train-auc:0.97281	eval-auc:0.97020
[200]	train-auc:0.97518	eval-auc:0.97166
[300]	train-auc:0.97699	eval-auc:0.97258
[400]	train-auc:0.97848	eval-auc:0.97314
[500]	train-auc:0.97979	eval-auc:0.97354
[600]	train-auc:0.98091	eval-auc:0.97378
[700]	train-auc:0.98190	eval-auc:0.97396
[800]	train-auc:0.98280	eval-auc:0.97408
[900]	train-auc:0.98361	eval-auc:0.97417
[1000]	train-auc:0.98439	eval-auc:0.97424
[1100]	train-auc:0.98512	eval-auc:0.97429
[1200]	train-auc:0.98582	eval-auc:0.97433
[1300]	train-auc:0.98644	eval-auc:0.97437
[1400]	train-auc:0.98705	eval-auc:0.97440
[1500]	train-auc:0.98766	eval-auc:0.97442
[1600]	train-auc:0.98823	eval-auc:0.97444
[1700]	train-auc:0.98874	eval-auc:0.97445

In [6]:
tr_df12 = pd.read_parquet("../artifacts/features/base/tr_df12.parquet")
tr_df16 = pd.read_parquet("../artifacts/features/base/tr_df16.parquet")

In [7]:
len_12 = len(tr_df12)
tr_df12.equals(tr_df16.iloc[:len_12])

False

In [8]:
tr_df12.head()

,age,balance,day,duration,campaign,pdays,previous,target,contact_te,default_te,...,marital_x_poutcome_te,marital_x_previous_te,month_x_campaign_te,month_x_duration_te,month_x_pdays_te,month_x_poutcome_te,month_x_previous_te,pdays_x_poutcome_te,pdays_x_previous_te,previous_x_poutcome_te
0,42,7,25,117,3,-1,0,0,0.156326,0.121961,...,0.084241,0.084244,0.124602,0.002809,0.095284,0.095293,0.095283,0.101927,0.101937,0.101928
1,38,514,18,185,1,-1,0,0,0.043436,0.121961,...,0.084241,0.084244,0.131415,0.050000,0.090163,0.090173,0.090162,0.101927,0.101937,0.101928
2,36,602,14,111,2,-1,0,0,0.042518,0.121927,...,0.084684,0.084686,0.070335,0.000000,0.061908,0.061905,0.061906,0.101939,0.101947,0.101939
3,27,34,28,10,2,-1,0,0,0.042518,0.121927,...,0.148100,0.148102,0.070335,0.001745,0.061908,0.061905,0.061906,0.101939,0.101947,0.101939
4,26,889,3,902,1,-1,0,1,0.156326,0.121961,...,0.084241,0.084244,0.242127,0.400000,0.187368,0.187341,0.187357,0.101927,0.101937,0.101928

In [9]:
tr_df16.head()

,age,balance,day,duration,campaign,pdays,previous,target,job_te,marital_te,...,duration_campaign_te,duration_pdays_te,duration_previous_te,duration_poutcome_te,campaign_pdays_te,campaign_previous_te,campaign_poutcome_te,pdays_previous_te,pdays_poutcome_te,previous_poutcome_te
0,42,7,25,117,3,-1,0,0,0.117947,0.101688,...,0.000000,0.002872,0.002872,0.002872,0.092219,0.092222,0.092231,0.101179,0.101172,0.101172
1,38,514,18,185,1,-1,0,0,0.068013,0.101921,...,0.055833,0.025876,0.025876,0.025876,0.126205,0.126198,0.126194,0.101301,0.101292,0.101293
2,36,602,14,111,2,-1,0,0,0.067547,0.102144,...,0.000000,0.000573,0.000573,0.000573,0.095177,0.095173,0.095170,0.101555,0.101552,0.101552
3,27,34,28,10,2,-1,0,0,0.335827,0.169128,...,0.000000,0.003702,0.003702,0.003702,0.095288,0.095291,0.095293,0.101301,0.101292,0.101293
4,26,889,3,902,1,-1,0,1,0.117907,0.102144,...,0.696203,0.593023,0.593023,0.593023,0.126387,0.126386,0.126396,0.101555,0.101552,0.101552