### Configuration

In [6]:
import sys, os
import polars as pl
pl.Config.set_tbl_rows(700)
pl.Config.set_tbl_cols(700)

sys.path.append("../..")

### debug code

In [32]:
import os
import json
from collections import Counter
from datetime import datetime, timezone, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl

runs_root = Path("../../runs")
run_dirs = sorted(p for p in runs_root.iterdir() if p.is_dir())

oof_cols = []
test_cols = []
oof_arrays = []
test_arrays = []

for rd in run_dirs:
    oof_path = rd / "oof.npy"
    test_path = rd / "test.npy"
    if not (oof_path.exists() and test_path.exists()):
        continue

    name = rd.name  # 例: xgb-031-trl6-5fold-s42
    oof = np.load(oof_path)[:750_000]
    test = np.load(test_path)[:250_000]

    # カラム名を run 名にして格納
    oof_arrays.append(oof)
    test_arrays.append(test)
    oof_cols.append(name)
    test_cols.append(name)

# === 横結合して DataFrame 化 ===
oof_df = pl.DataFrame({c: a for c, a in zip(oof_cols, oof_arrays)})
test_df = pl.DataFrame({c: a for c, a in zip(test_cols, test_arrays)})


# === row_id を追加 ===
oof_df = oof_df.with_row_index("row_id")

# === targetを追加 ===
lf = pl.scan_parquet("../../artifacts/features/033/tr_df.parquet")
y = lf.select("target").collect()
oof_df = oof_df.with_columns(y)

### input cell

In [37]:
oof_df.describe()

shape: (9, 44)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ row ┆ hc- ┆ las ┆ lgb ┆ mlp ┆ mlp ┆ mlp ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ xgb ┆ tar │
│ tis ┆ _id ┆ 034 ┆ so- ┆ m-0 ┆ -03 ┆ -03 ┆ -04 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -02 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -03 ┆ -04 ┆ -04 ┆ -04 ┆ get │
│ tic ┆ --- ┆ --- ┆ 034 ┆ 42- ┆ 3-t ┆ 9-t ┆ 1-t ┆ 3-t ┆ 3-t ┆ 3-t ┆ 3-t ┆ 3-t ┆ 3-t ┆ 6-t ┆ 6-t ┆ 6-t ┆ 6-t ┆ 6-t ┆ 7-t ┆ 7-t ┆ 7-t ┆ 7-t ┆ 7-t ┆ 0-t ┆ 0-t ┆ 1-t ┆ 1-t ┆ 1-t ┆ 1-t ┆ 1-t ┆ 2-t ┆ 3-t ┆ 3-t ┆ 5-t ┆ 5-t ┆ 6-t ┆ 7-t ┆ 8-t ┆ 9-t ┆ 0-t ┆ 2-t ┆ 2-t ┆ --- │
│ --- ┆ f64 ┆ f64 ┆ -tr ┆ trl ┆ rl2 ┆ rl1 ┆ rl7 ┆ rl3 ┆ rl3 ┆ rl4 ┆ rl5 ┆ rl5 ┆ rl5 ┆ rl1 ┆ rl1 ┆ rl1 ┆ rl1 ┆ rl2 ┆ rl1 ┆ rl1 ┆ rl1 ┆ rl1 ┆ rl2 ┆ rl1 ┆ rl2 ┆ rl6 ┆ rl6 ┆ rl6 ┆ rl6 ┆ rl6 ┆ rl1 ┆ rl1 ┆ rl7 ┆ rl2 ┆ rl5 ┆ rl4 ┆ rl7 ┆ rl5 ┆ rl1 ┆ rl1 ┆ rl5 ┆ rl6 ┆ f64 │
│ str ┆     ┆     ┆ l5- ┆ 1-5 ┆ -5f ┆ 8-5 ┆ -5f ┆ 2-s ┆ 6-s ┆ 4-s ┆ 1-s ┆ 7-s ┆ 8-s ┆ 6-s ┆ 7-s ┆ 8-s ┆ 9-s ┆ 1-s ┆ 4-s ┆ 5-s ┆ 6-s ┆ 7-s ┆ 2-s ┆ 9-s ┆ 0-s ┆ -10 ┆ -15 ┆ -20 ┆ -5f ┆ -7f ┆ 9-1 ┆ 7-5 ┆ -10 ┆ 0-5 ┆ -5f ┆ -5f ┆ -5f ┆ -5f ┆ 6-5 ┆ 7-5 ┆ -5f ┆ -5f ┆     │
│     ┆     ┆     ┆ 5fo ┆ fol ┆ old ┆ fol ┆ old ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ 42  ┆ fol ┆ fol ┆ fol ┆ old ┆ old ┆ 0fo ┆ fol ┆ fol ┆ fol ┆ old ┆ old ┆ old ┆ old ┆ fol ┆ fol ┆ old ┆ old ┆     │
│     ┆     ┆     ┆ ld- ┆ d-s ┆ -s4 ┆ d-s ┆ -s4 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ d-s ┆ d-s ┆ d-s ┆ -s4 ┆ -s4 ┆ ld- ┆ d-s ┆ d-s ┆ d-s ┆ -s4 ┆ -s4 ┆ -s4 ┆ -s4 ┆ d-s ┆ d-s ┆ -s4 ┆ -s4 ┆     │
│     ┆     ┆     ┆ s42 ┆ 42  ┆ 2   ┆ 42  ┆ 2   ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ 42  ┆ 42  ┆ 42  ┆ 2   ┆ 2   ┆ s42 ┆ 42  ┆ 42  ┆ 42  ┆ 2   ┆ 2   ┆ 2   ┆ 2   ┆ 42  ┆ 42  ┆ 2   ┆ 2   ┆     │
│     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 ┆ 750 │
│ nt  ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 │
│     ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆ .0  │
│ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ 374 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 │
│ n   ┆ 999 ┆ 187 ┆ 206 ┆ 202 ┆ 247 ┆ 216 ┆ 238 ┆ 198 ┆ 199 ┆ 193 ┆ 186 ┆ 196 ┆ 194 ┆ 179 ┆ 186 ┆ 194 ┆ 193 ┆ 174 ┆ 194 ┆ 194 ┆ 193 ┆ 191 ┆ 193 ┆ 179 ┆ 179 ┆ 200 ┆ 200 ┆ 200 ┆ 189 ┆ 200 ┆ 200 ┆ 204 ┆ 201 ┆ 203 ┆ 202 ┆ 201 ┆ 194 ┆ 195 ┆ 199 ┆ 148 ┆ 192 ┆ 193 ┆ 206 │
│     ┆ .5  ┆ 05  ┆ 51  ┆ 18  ┆ 25  ┆ 98  ┆ 55  ┆ 13  ┆ 4   ┆ 17  ┆ 4   ┆ 98  ┆ 93  ┆ 67  ┆ 67  ┆ 12  ┆ 89  ┆ 64  ┆ 86  ┆ 63  ┆ 56  ┆ 72  ┆ 15  ┆ 72  ┆ 64  ┆ 72  ┆ 53  ┆ 56  ┆ 61  ┆ 19  ┆ 71  ┆ 54  ┆ 37  ┆ 29  ┆ 2   ┆ 74  ┆ 89  ┆ 41  ┆ 97  ┆ 66  ┆ 43  ┆ 38  ┆ 51  │
│ std ┆ 216 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.2 ┆ 0.3 │
│     ┆ 506 ┆ 591 ┆ 181 ┆ 584 ┆ 624 ┆ 531 ┆ 603 ┆ 600 ┆ 605 ┆ 612 ┆ 628 ┆ 608 ┆ 617 ┆ 586 ┆ 586 ┆ 574 ┆ 581 ┆ 606 ┆ 596 ┆ 601 ┆ 607 ┆ 622 ┆ 613 ┆ 570 ┆ 570 ┆ 614 ┆ 615 ┆ 614 ┆ 597 ┆ 610 ┆ 611 ┆ 606 ┆ 605 ┆ 476 ┆ 504 ┆ 481 ┆ 580 ┆ 582 ┆ 581 ┆ 740 ┆ 588 ┆ 604 ┆ 257 │
│     ┆ .49 ┆ 7   ┆ 67  ┆ 08  ┆ 2   ┆ 03  ┆ 23  ┆ 81  ┆ 24  ┆ 07  ┆ 6   ┆ 58  ┆ 18  ┆ 9   ┆ 19  ┆ 62  ┆ 01  ┆ 72  ┆ 89  ┆ 48  ┆ 68  ┆ 35  ┆ 77  ┆ 82  ┆ 41  ┆ 58  ┆ 82  ┆ 06  ┆ 23  ┆ 61  ┆ 09  ┆ 07  ┆ 01  ┆ 55  ┆ 28  ┆ 08  ┆ 8   ┆ 22  ┆ 21  ┆ 96  ┆ 12  ┆ 1   ┆ 21  │
│     ┆ 528 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ min ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.6 ┆ 1.5 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 6.8 ┆ 0.0 ┆ 1.9 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 4.3 ┆ 2.5 ┆ 2.4 ┆ 4.6 ┆ 4.6 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆     ┆ 000 ┆ 205 ┆ 066 ┆ 286 ┆     ┆     ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 953 ┆ 000 ┆ 221 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 083 ┆ 160 ┆ 459 ┆ 109 ┆ 022 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 242 ┆ 000 ┆ 000 ┆     │
│     ┆     ┆ 04  ┆ 86  ┆ e-7 ┆ e-9 ┆     ┆     ┆ 02  ┆ 05  ┆ 03  ┆ 01  ┆ 02  ┆ 01  ┆ 02  ┆ e-7 ┆ 01  ┆ e-7 ┆ 02  ┆ 03  ┆ 03  ┆ 03  ┆ 01  ┆ 02  ┆ 05  ┆ 04  ┆ e-7 ┆ e-7 ┆ e-7 ┆ e-7 ┆ e-7 ┆ 01  ┆ 01  ┆ 07  ┆ 01  ┆ 11  ┆ 04  ┆ 03  ┆ 03  ┆ 06  ┆ e-7 ┆ 08  ┆ 01  ┆     │
│ 25% ┆ 187 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆ 500 ┆ 001 ┆ 208 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 001 ┆ 001 ┆ 001 ┆ 002 ┆ 003 ┆ 003 ┆ 002 ┆ 002 ┆ 002 ┆ 000 ┆ 001 ┆ 001 ┆     │
│     ┆ .0  ┆ 41  ┆ 73  ┆ 61  ┆ 57  ┆ 76  ┆ 21  ┆ 52  ┆ 63  ┆ 33  ┆ 05  ┆ 26  ┆ 09  ┆ 26  ┆ 23  ┆ 42  ┆ 05  ┆ 37  ┆ 45  ┆ 46  ┆ 37  ┆ 19  ┆ 34  ┆ 71  ┆ 7   ┆ 87  ┆ 85  ┆ 87  ┆ 93  ┆ 93  ┆ 28  ┆ 36  ┆ 68  ┆ 59  ┆ 85  ┆ 06  ┆ 26  ┆ 47  ┆ 66  ┆ 29  ┆ 64  ┆ 13  ┆     │
│ 50% ┆ 375 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆ 000 ┆ 008 ┆ 214 ┆ 006 ┆ 006 ┆ 008 ┆ 004 ┆ 009 ┆ 009 ┆ 008 ┆ 006 ┆ 008 ┆ 007 ┆ 007 ┆ 008 ┆ 008 ┆ 008 ┆ 007 ┆ 008 ┆ 008 ┆ 007 ┆ 007 ┆ 007 ┆ 009 ┆ 009 ┆ 007 ┆ 007 ┆ 007 ┆ 007 ┆ 007 ┆ 008 ┆ 008 ┆ 009 ┆ 016 ┆ 018 ┆ 017 ┆ 011 ┆ 012 ┆ 013 ┆ 001 ┆ 008 ┆ 007 ┆     │
│     ┆ .0  ┆ 53  ┆ 52  ┆ 57  ┆ 91  ┆ 48  ┆ 13  ┆ 32  ┆ 48  ┆ 49  ┆ 94  ┆ 42  ┆ 6   ┆ 63  ┆ 08  ┆ 86  ┆ 08  ┆ 62  ┆ 59  ┆ 35  ┆ 97  ┆ 13  ┆ 71  ┆ 46  ┆ 52  ┆ 18  ┆ 03  ┆ 17  ┆ 28  ┆ 4   ┆ 51  ┆ 91  ┆ 32  ┆ 76  ┆ 05  ┆ 38  ┆ 99  ┆ 84  ┆ 31  ┆ 92  ┆ 99  ┆ 43  ┆     │
│ 75% ┆ 562 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆ 499 ┆ 458 ┆ 593 ┆ 517 ┆ 604 ┆ 725 ┆ 636 ┆ 482 ┆ 477 ┆ 448 ┆ 396 ┆ 467 ┆ 445 ┆ 441 ┆ 465 ┆ 503 ┆ 493 ┆ 396 ┆ 472 ┆ 463 ┆ 449 ┆ 420 ┆ 439 ┆ 466 ┆ 467 ┆ 465 ┆ 462 ┆ 465 ┆ 459 ┆ 470 ┆ 473 ┆ 494 ┆ 484 ┆ 736 ┆ 668 ┆ 718 ┆ 505 ┆ 494 ┆ 516 ┆ 156 ┆ 482 ┆ 465 ┆     │
│     ┆ .0  ┆ 64  ┆ 4   ┆ 81  ┆ 97  ┆ 99  ┆ 91  ┆ 13  ┆ 06  ┆ 86  ┆ 29  ┆ 43  ┆ 67  ┆ 44  ┆ 76  ┆ 06  ┆ 61  ┆ 23  ┆ 38  ┆ 05  ┆ 77  ┆ 83  ┆ 74  ┆ 69  ┆ 97  ┆ 14  ┆ 16  ┆ 48  ┆ 83  ┆ 62  ┆ 22  ┆ 78  ┆ 63  ┆ 17  ┆ 64  ┆ 85  ┆ 55  ┆ 19  ┆ 54  ┆ 37  ┆ 13  ┆ 06  ┆     │
│ max ┆ 749 ┆ 0.9 ┆ 0.8 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 1.0 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 0.9 ┆ 1.0 │
│     ┆ 999 ┆ 986 ┆ 624 ┆ 982 ┆ 997 ┆ 999 ┆     ┆ 988 ┆ 986 ┆ 989 ┆ 992 ┆ 992 ┆ 991 ┆ 986 ┆ 988 ┆ 986 ┆ 991 ┆ 986 ┆ 994 ┆ 993 ┆ 991 ┆ 993 ┆ 993 ┆ 984 ┆ 983 ┆ 997 ┆ 996 ┆ 997 ┆ 995 ┆ 995 ┆ 989 ┆ 991 ┆ 982 ┆ 994 ┆ 987 ┆ 994 ┆ 997 ┆ 991 ┆ 985 ┆ 999 ┆ 985 ┆ 993 ┆     │
│     ┆ .0  ┆ 11  ┆ 2   ┆ 72  ┆ 73  ┆ 5   ┆     ┆ 45  ┆ 86  ┆ 15  ┆ 91  ┆ 27  ┆ 72  ┆ 29  ┆ 69  ┆ 42  ┆ 03  ┆ 57  ┆ 01  ┆ 5   ┆ 5   ┆ 8   ┆ 89  ┆ 58  ┆ 95  ┆ 28  ┆ 37  ┆ 38  ┆ 32  ┆ 03  ┆ 35  ┆ 95  ┆ 47  ┆ 06  ┆ 14  ┆ 5   ┆ 41  ┆ 62  ┆ 45  ┆ 46  ┆ 76  ┆ 19  ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [30]:
coef_list = result["fi_mean"]
coef_arr = np.stack(coef_list, axis=0)
abs_coef_mean = np.mean(np.abs(coef_arr), axis=0).ravel()
print(len(abs_coef_mean))

19

In [31]:
trainer.features

['hc-034',
 'xgb-023-trl32-s42',
 'xgb-023-trl36-s42',
 'xgb-023-trl44-s42',
 'xgb-023-trl51-s42',
 'xgb-023-trl57-s42',
 'xgb-023-trl58-s42',
 'xgb-026-trl16-s42',
 'xgb-026-trl17-s42',
 'xgb-026-trl18-s42',
 'xgb-026-trl19-s42',
 'xgb-026-trl21-s42',
 'xgb-027-trl14-s42',
 'xgb-027-trl15-s42',
 'xgb-027-trl16-s42',
 'xgb-027-trl17-s42',
 'xgb-027-trl22-s42',
 'xgb-030-trl19-s42',
 'xgb-030-trl20-s42']

In [28]:
pl.DataFrame({"x": abs_coef_mean.get()})

shape: (19, 1)
┌──────────┐
│ x        │
│ ---      │
│ f32      │
╞══════════╡
│ 0.218152 │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.000012 │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
│ 0.0      │
└──────────┘

In [40]:
import kaggle

In [41]:
help(kaggle)

Help on package kaggle:

NAME
    kaggle - # coding=utf-8

PACKAGE CONTENTS
    api (package)
    cli
    configuration
    models (package)
    test (package)

DATA
    api = <kaggle.api.kaggle_api_extended.KaggleApi object>

FILE
    /home/hanse/miniconda3/envs/rapids-25.08/lib/python3.13/site-packages/kaggle/__init__.py

In [43]:
api = kaggle.KaggleApi()
api.authenticate()